name: 发布pity
on:
  push:
    branches:
      - main # 只在main上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE
jobs:

  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@main

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "*"
          target: "/home/tester/pity/"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /data/version-manager && pip3 install -r requirements.txt --user && pkill gunicorn